package hooks

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	pb "WantasticCore/internal/types"

	"github.com/rs/zerolog/log"
)

const maxBackupSize = 10 << 20 // 10 MB

func writeBackupJSONError(w http.ResponseWriter, statusCode int, message string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(statusCode)
	_ = json.NewEncoder(w).Encode(map[string]string{"error": message})
}

// HandleBackupUpload handles POST /hooks/backup?token=XXX
//
// Security model:
//   - Token is a peer-scoped backup token generated by GenerateBackupToken
//   - Token is stored server-side and reused by scheduled MikroTik backups
//   - Regenerating the token rotates the previous peer token out
//   - The hook validates the token via gRPC UploadSnapshotBackup
//   - Max upload: 10 MB
//   - No session cookie needed (for headless MikroTik devices)
func (h *Handler) HandleBackupUpload(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost && r.Method != http.MethodPut {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	token := r.URL.Query().Get("token")
	if token == "" {
		auth := r.Header.Get("Authorization")
		if after, ok := strings.CutPrefix(auth, "Bearer "); ok {
			token = after
		}
	}
	if token == "" || len(token) < 16 {
		log.Warn().Str("remote", r.RemoteAddr).Msg("backup upload: missing or short token")
		// RouterOS /tool fetch treats 401 without WWW-Authenticate as malformed.
		// This endpoint uses bearer-style upload tokens, not HTTP auth challenges,
		// so malformed/missing tokens are reported as a plain bad request.
		writeBackupJSONError(w, http.StatusBadRequest, "missing or invalid token")
		return
	}

	// Read the upload body (max 10 MB)
	body, err := io.ReadAll(io.LimitReader(r.Body, maxBackupSize+1))
	if err != nil {
		writeBackupJSONError(w, http.StatusBadRequest, "read failed")
		return
	}
	if len(body) > maxBackupSize {
		writeBackupJSONError(w, http.StatusRequestEntityTooLarge, "file too large (max 10 MB)")
		return
	}
	if len(body) == 0 {
		writeBackupJSONError(w, http.StatusBadRequest, "empty body")
		return
	}

	// Build filename from query params or defaults
	peerName := sanitizeFilename(r.URL.Query().Get("name"))
	filename := r.URL.Query().Get("filename")
	if filename == "" {
		filename = fmt.Sprintf("%s-backup-%s.rsc", peerName, time.Now().Format("2006-01-02"))
	} else {
		filename = sanitizeFilename(filename)
	}

	if h.services.WUSP == nil {
		writeBackupJSONError(w, http.StatusServiceUnavailable, "service unavailable")
		return
	}

	// Validate token and store backup via in-process service call.
	// The core's UploadSnapshotBackup checks the peer backup token and stores
	// the uploaded RouterOS export against that peer's snapshot record.
	ctx, cancel := context.WithTimeout(r.Context(), 15*time.Second)
	defer cancel()

	resp, err := h.services.WUSP.UploadSnapshotBackup(ctx, &pb.UploadSnapshotBackupRequest{
		UploadToken: token,
		BackupFile:  body,
		BackupName:  filename,
	})
	if err != nil {
		log.Error().Err(err).Str("remote", r.RemoteAddr).Msg("backup upload: gRPC error")
		writeBackupJSONError(w, http.StatusInternalServerError, "upload failed")
		return
	}
	if !resp.Success {
		log.Warn().Str("error", resp.Error).Str("remote", r.RemoteAddr).Msg("backup upload: rejected")
		// Invalid/expired/rotated backup tokens are authorization failures, but not
		// HTTP auth challenges. Use 403 so RouterOS does not expect a
		// WWW-Authenticate header.
		writeBackupJSONError(w, http.StatusForbidden, resp.Error)
		return
	}

	log.Info().
		Str("filename", filename).
		Int("size", len(body)).
		Str("remote", r.RemoteAddr).
		Msg("backup upload: success")

	w.Header().Set("Content-Type", "application/json")
	fmt.Fprintf(w, `{"success":true,"size":%d,"filename":"%s"}`, len(body), filename)
}

func sanitizeFilename(name string) string {
	name = strings.ReplaceAll(name, "/", "_")
	name = strings.ReplaceAll(name, "\\", "_")
	name = strings.ReplaceAll(name, "..", "_")
	name = strings.ReplaceAll(name, " ", "-")
	if len(name) > 128 {
		name = name[:128]
	}
	if name == "" {
		name = "backup"
	}
	return name
}
