package userspace

import (
	"encoding/base64"
	"encoding/hex"
	"strconv"
	"strings"
	"time"

	"github.com/rs/zerolog/log"
)

// Clients generated by this portal use a 25s persistent keepalive, so three
// missed authenticated packets is a strong offline signal without being twitchy.
const peerOnlineThreshold = 75 * time.Second

type ipcSnapshot struct {
	raw            string
	fetchedAt      time.Time
	peers          map[string]*PeerStatus
	endpointToPeer map[string]string
	peerCount      int
	connectedPeers int
	totalTxBytes   uint64
	totalRxBytes   uint64
	lastActivity   time.Time
}

func parseIPCSnapshot(ipcGet string, now time.Time) *ipcSnapshot {
	snapshot := &ipcSnapshot{
		raw:            ipcGet,
		fetchedAt:      now,
		peers:          make(map[string]*PeerStatus),
		endpointToPeer: make(map[string]string),
	}

	var currentPeerKey string
	var lastHandshakeSec, lastHandshakeNsec int64
	var lastAuthenticatedSec, lastAuthenticatedNsec int64
	var rxBytes, txBytes int64
	var endpoint string
	var currentAssignedIP string
	var currentAllowedIPs []string
	inPeer := false

	finalizePeer := func() {
		if !inPeer || currentPeerKey == "" {
			return
		}

		publicKey := normalizeIPCPublicKey(currentPeerKey)
		var lastHandshake time.Time
		if lastHandshakeSec > 0 {
			lastHandshake = time.Unix(lastHandshakeSec, lastHandshakeNsec)
		}
		var lastAuthenticatedPacket time.Time
		if lastAuthenticatedSec > 0 {
			lastAuthenticatedPacket = time.Unix(lastAuthenticatedSec, lastAuthenticatedNsec)
		}
		recentActivity := lastAuthenticatedPacket
		if recentActivity.IsZero() {
			recentActivity = lastHandshake
		}

		hasEndpoint := endpoint != ""
		isOnline := hasEndpoint && !recentActivity.IsZero() && now.Sub(recentActivity) < peerOnlineThreshold

		status := &PeerStatus{
			PublicKey:                   publicKey,
			LastHandshakeTime:           lastHandshake,
			LastAuthenticatedPacketTime: recentActivity,
			RxBytes:                     rxBytes,
			TxBytes:                     txBytes,
			IsOnline:                    isOnline,
			HasEndpoint:                 hasEndpoint,
			Endpoint:                    endpoint,
			AssignedIP:                  currentAssignedIP,
			AllowedIPs:                  append([]string(nil), currentAllowedIPs...),
		}

		snapshot.peers[publicKey] = status
		snapshot.peerCount++
		if isOnline {
			snapshot.connectedPeers++
		}
		if txBytes > 0 {
			snapshot.totalTxBytes += uint64(txBytes)
		}
		if rxBytes > 0 {
			snapshot.totalRxBytes += uint64(rxBytes)
		}
		if lastHandshake.After(snapshot.lastActivity) {
			snapshot.lastActivity = lastHandshake
		}
		if endpoint != "" {
			snapshot.endpointToPeer[endpoint] = publicKey
		}
	}

	start := 0
	for i := 0; i <= len(ipcGet); i++ {
		if i != len(ipcGet) && ipcGet[i] != '\n' {
			continue
		}

		line := ipcGet[start:i]
		start = i + 1

		switch {
		case strings.HasPrefix(line, "public_key="):
			finalizePeer()

			currentPeerKey = line[11:]
			lastHandshakeSec = 0
			lastHandshakeNsec = 0
			lastAuthenticatedSec = 0
			lastAuthenticatedNsec = 0
			rxBytes = 0
			txBytes = 0
			endpoint = ""
			currentAssignedIP = ""
			currentAllowedIPs = nil
			inPeer = true
		case !inPeer:
			continue
		case strings.HasPrefix(line, "last_handshake_time_sec="):
			lastHandshakeSec, _ = strconv.ParseInt(line[24:], 10, 64)
		case strings.HasPrefix(line, "last_handshake_time_nsec="):
			lastHandshakeNsec, _ = strconv.ParseInt(line[25:], 10, 64)
		case strings.HasPrefix(line, "last_authenticated_packet_time_sec="):
			lastAuthenticatedSec, _ = strconv.ParseInt(line[35:], 10, 64)
		case strings.HasPrefix(line, "last_authenticated_packet_time_nsec="):
			lastAuthenticatedNsec, _ = strconv.ParseInt(line[36:], 10, 64)
		case strings.HasPrefix(line, "rx_bytes="):
			rxBytes, _ = strconv.ParseInt(line[9:], 10, 64)
		case strings.HasPrefix(line, "tx_bytes="):
			txBytes, _ = strconv.ParseInt(line[9:], 10, 64)
		case strings.HasPrefix(line, "endpoint="):
			if len(line) > 9 {
				endpoint = line[9:]
			}
		case strings.HasPrefix(line, "allowed_ip="):
			allowedIP := line[11:]
			if currentAssignedIP == "" {
				currentAssignedIP = splitAllowedIP(allowedIP)
			}
			currentAllowedIPs = append(currentAllowedIPs, allowedIP)
		}
	}

	finalizePeer()
	return snapshot
}

func normalizeIPCPublicKey(key string) string {
	key = strings.TrimSpace(key)
	if pubKeyBytes, err := hex.DecodeString(key); err == nil {
		return base64.StdEncoding.EncodeToString(pubKeyBytes)
	}

	log.Warn().Str("hex_key", key).Msg("Failed to decode hex public key from IPC")
	return key
}

func splitAllowedIP(allowedIP string) string {
	if idx := strings.IndexByte(allowedIP, '/'); idx != -1 {
		return allowedIP[:idx]
	}
	return allowedIP
}

func copyPeerStatus(status *PeerStatus) *PeerStatus {
	if status == nil {
		return nil
	}

	clone := *status
	clone.AllowedIPs = append([]string(nil), status.AllowedIPs...)
	return &clone
}

func copyPeerStatusMap(peers map[string]*PeerStatus) map[string]*PeerStatus {
	cloned := make(map[string]*PeerStatus, len(peers))
	for publicKey, status := range peers {
		cloned[publicKey] = copyPeerStatus(status)
	}
	return cloned
}
